
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Krish
 */
public class AddBag extends javax.swing.JFrame {

    /**
     * Creates new form AddBag
     */
    public AddBag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bagID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        txtBagID = new javax.swing.JTextField();
        txtBagName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        Quantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddbag = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add New Bag...........");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 38, 249, -1));

        bagID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bagID.setText("Bag ID");
        getContentPane().add(bagID, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 112, 62, -1));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Name.setText("Name");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 157, 62, -1));

        Category.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Category.setText("Category");
        getContentPane().add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 206, 62, -1));

        Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Price.setText("Price");
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 250, 53, -1));
        getContentPane().add(txtBagID, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 109, 243, -1));
        getContentPane().add(txtBagName, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 157, 243, -1));
        getContentPane().add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 203, 243, -1));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 247, 243, -1));

        Quantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Quantity.setText("Quantity");
        getContentPane().add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 290, -1, -1));
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 287, 243, -1));

        btnAddbag.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddbag.setText("Add Bag");
        btnAddbag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddbagActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddbag, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 90, 30));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -60, 640, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddbagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddbagActionPerformed
        
        String bagId = txtBagID.getText();
        String bagName = txtBagName.getText();
        String category = txtCategory.getText();
        String price = txtPrice.getText();
        String quantity = txtQuantity.getText();

    // Logic to insert the new bag into the database
    JOptionPane.showMessageDialog(this, "New bag added successfully!");

    }//GEN-LAST:event_btnAddbagActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        // Hide current form
    this.setVisible(false);
    
    // Open CashierMenu
    CashierMenu cashierMenu = new CashierMenu();
    cashierMenu.setVisible(true);
    
    // Dispose current form (optional)
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel bagID;
    private javax.swing.JButton btnAddbag;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtBagID;
    private javax.swing.JTextField txtBagName;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
