/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Krish
 */
public class CashierMenu extends javax.swing.JFrame {

    /**
     * Creates new form CashierMenu
     */
    public CashierMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewBags = new javax.swing.JButton();
        btnAddBags = new javax.swing.JButton();
        btnSearchBags = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cashier Menu.........");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 82, 396, -1));

        btnViewBags.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewBags.setText("View Bags");
        btnViewBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBagsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        btnAddBags.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddBags.setText("Add Bag");
        btnAddBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBagsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        btnSearchBags.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearchBags.setText("Search Bags");
        btnSearchBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBagsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBagsActionPerformed
        
        ViewBags viewBagsFrame = new ViewBags();
        viewBagsFrame.setVisible(true); // Open the ViewBags JFrame
    }//GEN-LAST:event_btnViewBagsActionPerformed

    private void btnAddBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBagsActionPerformed
        
        AddBag addBagFrame = new AddBag();
        addBagFrame.setVisible(true); // Open AddBag JFrame
    }//GEN-LAST:event_btnAddBagsActionPerformed

    private void btnSearchBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBagsActionPerformed
        
        SearchBags searchBagsFrame = new SearchBags();
        searchBagsFrame.setVisible(true); // Open SearchBags JFrame
    }//GEN-LAST:event_btnSearchBagsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBags;
    private javax.swing.JButton btnSearchBags;
    private javax.swing.JButton btnViewBags;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
