import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Krisha
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        radioCashier = new javax.swing.JRadioButton();
        radioManager = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("The Little Bag Shop......");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 404, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 116, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Select Role");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 116, 24));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("User Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 116, 24));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 257, 32));

        roleGroup.add(radioCashier);
        radioCashier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioCashier.setForeground(new java.awt.Color(255, 255, 255));
        radioCashier.setText("Cashier");
        radioCashier.setActionCommand("radioCashier");
        radioCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCashierActionPerformed(evt);
            }
        });
        getContentPane().add(radioCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        roleGroup.add(radioManager);
        radioManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioManager.setForeground(new java.awt.Color(255, 255, 255));
        radioManager.setText("Manager");
        radioManager.setActionCommand("radioManager");
        radioManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioManagerActionPerformed(evt);
            }
        });
        getContentPane().add(radioManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setActionCommand("BtnLogin");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 117, 33));
        btnLogin.getAccessibleContext().setAccessibleName("BtnLogin");

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 117, 33));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 257, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -30, 670, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        
        // 1. Get user input
    String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();
    
    // 2. Validate role selection
    if (!radioCashier.isSelected() && !radioManager.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select a role!");
        return;
    }
    
    // 3. Check credentials
    if (radioCashier.isSelected() && username.equals("cashier1") && password.equals("password")) {
        JOptionPane.showMessageDialog(this, "Login successful as Cashier");
        this.setVisible(false); // Hide login window
        new CashierMenu().setVisible(true); // Open cashier menu
        this.dispose(); // Release resources
    } 
    else if (radioManager.isSelected() && username.equals("admin") && password.equals("admin123")) {
        JOptionPane.showMessageDialog(this, "Login successful as Manager");
        this.setVisible(false);
        new ManagerMenu().setVisible(true);
        this.dispose();
    } 
    else {
        JOptionPane.showMessageDialog(this, "Invalid credentials!");
    }

    }//GEN-LAST:event_BtnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void radioCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCashierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCashierActionPerformed

    private void radioManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioManagerActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
         // Get user input
    String username = txtUsername.getText();
    String password = new String(txtPassword.getPassword());

    // Check which role is selected
    String role = "";
    if (radioCashier.isSelected()) {
        role = "Cashier";
    } else if (radioManager.isSelected()) {
        role = "Manager";
    }

     // Validate login (dummy check)
    if (role.equals("Cashier") && username.equals("cashier1") && password.equals("password")) {
        JOptionPane.showMessageDialog(this, "Login successful as Cashier");
        // Open Cashier menu
        CashierMenu cashierMenu = new CashierMenu();
        cashierMenu.setVisible(true);
        this.dispose(); // Close login page
    } else if (role.equals("Manager") && username.equals("admin") && password.equals("admin123")) {
        JOptionPane.showMessageDialog(this, "Login successful as Manager");
        // Open Manager menu
        ManagerMenu managerMenu = new ManagerMenu();
        managerMenu.setVisible(true);
        this.dispose(); // Close login page
    } else {
        JOptionPane.showMessageDialog(this, "Invalid username, password or role!");
    }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radioCashier;
    private javax.swing.JRadioButton radioManager;
    private javax.swing.ButtonGroup roleGroup;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private static class radioCashier {

        private static boolean isSelected() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public radioCashier() {
        }
    }

    private static class txtPassword {

        private static String getPassword() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtPassword() {
        }
    }

    private static class radioManager {

        private static boolean isSelected() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public radioManager() {
        }
    }
}
