/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Krish
 */
public class ManagerMenu extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMenu
     */
    public ManagerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewBags = new javax.swing.JButton();
        btnAddBag = new javax.swing.JButton();
        btnSearchBags = new javax.swing.JButton();
        btnCreateCashier = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manager Menu.........");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 279, -1));

        btnViewBags.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewBags.setText("View Bags");
        btnViewBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBagsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        btnAddBag.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddBag.setText("Add Bag");
        btnAddBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBagActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddBag, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        btnSearchBags.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchBags.setText("Search Bags");
        btnSearchBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBagsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 255, -1, -1));

        btnCreateCashier.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCreateCashier.setText("Create Cashier");
        btnCreateCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCashierActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 630, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBagsActionPerformed
        
        SearchBags searchBagsFrame = new SearchBags();
        searchBagsFrame.setVisible(true); // Open SearchBags JFrame
    }//GEN-LAST:event_btnSearchBagsActionPerformed

    private void btnAddBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBagActionPerformed
        
        AddBag addBagFrame = new AddBag();
        addBagFrame.setVisible(true); // Open AddBag JFrame
    }//GEN-LAST:event_btnAddBagActionPerformed

    private void btnViewBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBagsActionPerformed
        
        ViewBags viewBagsFrame = new ViewBags();
        viewBagsFrame.setVisible(true); // Open ViewBags JFrame
    }//GEN-LAST:event_btnViewBagsActionPerformed

    private void btnCreateCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCashierActionPerformed
        
        CreateCashier createCashierFrame = new CreateCashier();
        createCashierFrame.setVisible(true); // Open CreateCashier JFrame

    }//GEN-LAST:event_btnCreateCashierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBag;
    private javax.swing.JButton btnCreateCashier;
    private javax.swing.JButton btnSearchBags;
    private javax.swing.JButton btnViewBags;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
